# Generated by Django 4.1.3 on 2022-12-01 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Order Id')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('market_type', models.CharField(choices=[('SK', 'Simple Market'), ('CK', 'Complex Market')], max_length=5, verbose_name='Market Type')),
                ('number_of_bids', models.PositiveIntegerField(default=0, verbose_name='Number of Bids')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            
            options={
                'verbose_name_plural': 'Order Books',
            },
        ),
        migrations.CreateModel(
            name='OrderBookOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('yes_bid_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price for Yes')),
                ('no_bid_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price for No')),
                ('orderbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.orderbook', verbose_name='Order Book')),
            ],
            options={
                'verbose_name_plural': 'Order Books Options',
            },
        ),
    ]
