# Generated by Django 4.1.3 on 2022-12-01 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderBookOptions',
            new_name='OrderBookOption',
        ),
        migrations.RenameField(
            model_name='orderbook',
            old_name='date',
            new_name='event_date',
        ),
    ]
