# Generated by Django 4.1.3 on 2022-12-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_rename_orderbookoptions_orderbookoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
